from base import ProberForBertUtterCLS
from emo.emo import EMOProber
from genre_classification.genre_classification import GTZANProber
from instrument_classification.instrument_classification import NSynthIProber
from key_detect.key_detect import GSProber
from pitch_classification.pitch_classification import NSynthPProber
from vocal_technique_detection.vocal_technique_detection import VocalSetTProber